### ISSUE TITLE
根目录启动 npm run dev 报错

### ISSUE THREAD

**Issue by ZhangwenGmi** [liangfengbo/nodejs-koa-blog#22]
@liangfengbo 大佬，根目录启动项目的时候报错，麻烦看下怎么解决
![企业微信截图_15621396357888](https://user-images.githubusercontent.com/21217205/60572830-ff9c2300-9da8-11e9-9b15-1b50eff6f777.png)

**Comment by ZhangwenGmi** [comment]
仔细看了一下错误，自己解决了。一开始是端口占用，后台是mysql没设置用户名密码。。。不过还是谢谢大佬

**Comment by liangfengbo** [comment]
> 仔细看了一下错误，自己解决了。一开始是端口占用，后台是mysql没设置用户名密码。。。不过还是谢谢大佬

好的，谢谢提醒，我应该添加说明一下需要修改配置数据库的：）

**Comment by jshengqin** [comment]
刚接触不太懂，一直出现这个是什么问题 
SequelizeConnectionError: Unknown database 'boblog'
      at Promise.tap.then.catch.err (E:\nodeJs\project\boblog\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:133:19)
      at tryCatcher (E:\nodeJs\project\boblog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\nodeJs\project\boblog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\nodeJs\project\boblog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\nodeJs\project\boblog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\nodeJs\project\boblog\node_modules\bluebird\js\release\promise.js:725:18)
      at _drainQueueStep (E:\nodeJs\project\boblog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\nodeJs\project\boblog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\nodeJs\project\boblog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\nodeJs\project\boblog\node_modules\bluebird\js\release\async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
