### ISSUE TITLE
关于部署环境

### ISSUE THREAD

**Issue by zidingxiang628** [liangfengbo/nodejs-koa-blog#55]
请问大佬，这个项目只能部署在linux环境下是吗？ 
我在windows环境下 启动web 报错

**Comment by liangfengbo** [comment]
> 请问大佬，这个项目只能部署在linux环境下是吗？
> 我在windows环境下 启动web 报错

报什么错误？

**Comment by zidingxiang628** [comment]
754 verbose stack     at Promise._settlePromiseFromHandler (E:\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:524:17)
755 verbose pkgid inotify@1.4.6
756 verbose cwd E:\nodejs-koa-blog2\web
757 verbose Windows_NT 6.1.7601
758 verbose argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "dev"
759 verbose node v10.15.3
760 verbose npm  v6.4.1
761 error code EBADPLATFORM
762 error notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
763 error notsup Valid OS:    linux
763 error notsup Valid Arch:  any
763 error notsup Actual OS:   win32
763 error notsup Actual Arch: x64
764 verbose exit [ 1, true ]

**Comment by zidingxiang628** [comment]
按照百度找到的 执行 "npm install copy-webpack-plugin --save-dev"
现在是报 找不到  ./webpack.dll.conf.js' 这个文件 

 verbose lifecycle webapp@0.1.0~dll: CWD: E:\nodejs-koa-blog2\web
10 silly lifecycle webapp@0.1.0~dll: Args: [ '/d /s /c',
10 silly lifecycle   'webpack -p --progress --config ./webpack.dll.conf.js' ]
11 silly lifecycle webapp@0.1.0~dll: Returned: code: 1  signal: null
12 info lifecycle webapp@0.1.0~dll: Failed to exec dll script
13 verbose stack Error: webapp@0.1.0 dll: `webpack -p --progress --config ./webpack.dll.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (E:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid webapp@0.1.0

**Comment by zidingxiang628** [comment]
readme.md 中 # 启动前端项目命令如下，可是 scripts并没有 dev啊 
1. 在根目录下进入web项目：cd web，
2. 安装包，执行: npm install 命令，
3. 启动服务: npm run dev; 浏览器打开：http://localhost:8080/ 即可以访问。
 

 "name": "webapp",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "dll": "webpack -p --progress --config ./webpack.dll.conf.js",
    "test:unit": "vue-cli-service test:unit --watch"

**Comment by liangfengbo** [comment]
> readme.md 中 # 启动前端项目命令如下，可是 scripts并没有 dev啊
> 
> 1. 在根目录下进入web项目：cd web，
> 2. 安装包，执行: npm install 命令，
> 3. 启动服务: npm run dev; 浏览器打开：http://localhost:8080/ 即可以访问。
> 
> "name": "webapp",
> "version": "0.1.0",
> "private": true,
> "scripts": {
> "serve": "vue-cli-service serve",
> "build": "vue-cli-service build",
> "lint": "vue-cli-service lint",
> "dll": "webpack -p --progress --config ./webpack.dll.conf.js",
> "test:unit": "vue-cli-service test:unit --watch"

噢，应该启动命令是：yarn serve ，非常感谢指正，我马上更正

**Comment by Sunnyaya** [comment]
按照您的步骤启动项目，访问localhost:3000/v1，页面显示”not found“，也没有任何报错信息，这是什么原因呢

**Comment by liangfengbo** [comment]
> 按照您的步骤启动项目，访问localhost:3000/v1，页面显示”not found“，也没有任何报错信息，这是什么原因呢

现在可以拉取最新版，新增了ejs服务端模板输出，更多内容请看问题，打开：`http://localhost:3000/`就可以看到页面啦，谢谢支持：）

**Comment by Sunnyaya** [comment]
”拉取最新版“是什么意思？这是执行cnpm run dev命令以后的输出，麻烦您看一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fengbo Liang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 上午10:44
收件人:&nbsp;"liangfengbo/nodejs-koa-blog"<nodejs-koa-blog@noreply.github.com&gt;;
抄送:&nbsp;"℡ミ﹏尛樣╮"<1248673957@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [liangfengbo/nodejs-koa-blog] 关于部署环境 (#55)



 
按照您的步骤启动项目，访问localhost:3000/v1，页面显示”not found“，也没有任何报错信息，这是什么原因呢
  
现在可以拉取最新版，新增了ejs服务端模板输出，更多内容请看问题，打开：http://localhost:3000/就可以看到页面啦，谢谢支持：）

**Comment by liangfengbo** [comment]
> 按照您的步骤启动项目，访问localhost:3000/v1，页面显示”not found“，也没有任何报错信息，这是什么原因呢

jiu

> ”拉取最新版“是什么意思？这是执行cnpm run dev命令以后的输出，麻烦您看一下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Fengbo Liang"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月16日(星期一) 上午10:44 收件人:&nbsp;"liangfengbo/nodejs-koa-blog"<nodejs-koa-blog@noreply.github.com&gt;; 抄送:&nbsp;"℡ミ﹏尛樣╮"<1248673957@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [liangfengbo/nodejs-koa-blog] 关于部署环境 (#55) 按照您的步骤启动项目，访问localhost:3000/v1，页面显示”not found“，也没有任何报错信息，这是什么原因呢 现在可以拉取最新版，新增了ejs服务端模板输出，更多内容请看问题，打开：http://localhost:3000/就可以看到页面啦，谢谢支持：） — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯.. 就是来看最新的代码：[https://github.com/liangfengbo/nodejs-koa-blog](https://github.com/liangfengbo/nodejs-koa-blog)
